export const GET_TESTIMONIALS = '[GET_TESTIMONIALS] GET TESTIMONIALS';
export const GET_TESTIMONIALS_DONE = '[GET_TESTIMONIALS_DONE] GET TESTIMONIALS DONE ';
export const GET_TESTIMONIALS_FAILED = '[GET_TESTIMONIALS_FAILED] GET TESTIMONIALS FAILED';

export const TOGGLE_MENU = '[TOGGLE_MENU] TOGGLE MENU';

export const TOGGLE_CONTRAST = '[TOGGLE_CONTRAST] TOGGLE CONTRAST';

export const GET_CATEGORIES = '[GET_CATEGORIES] GET CATEGORIES';
export const GET_CATEGORIES_SUCCESS = '[GET_CATEGORIES_SUCCESS] GET CATEGORIES SUCCESS';
export const GET_CATEGORIES_FAILED = '[GET_CATEGORIES_FAILED] GET CATEGORIES FAILED';

export const GET_SELECTED_OFFERS = '[GET_SELECTED_OFFERS] GET SELECTED OFFERS';
export const GET_SELECTED_OFFERS_SUCCESS = '[GET_SELECTED_OFFERS_SUCCESS] GET SELECTED OFFERS SUCCESS';
export const GET_SELECTED_OFFERS_FAILED = '[GET_SELECTED_OFFERS_FAILED] GET SELECTED OFFERS FAILED';
